const express = require("express");
const router = express.Router();
const { protect } = require("../middleware/auth");
const { getLists, addCard, getCard, updateCard, deleteCard, moveCard } = require("../controllers/list");
router.get("/:boardId", protect, getLists);
router.post("/:listId/cards", protect, addCard);
router.get("/:listId/cards", protect, getCard);
router.put("/:listId/cards/:cardId", protect, updateCard);
router.delete("/:listId/cards/:cardId", protect, deleteCard);
module.exports = router;
